### ISSUE TITLE
carbon-lookup returns nodes on bad metric

### ISSUE THREAD

**Issue by TC-robV** [graphite-project/carbonate#125]
not sure if this is intended but for some reason when i lookup a metric i know is not in graphite carbon-lookup still returns nodes.

bad metric:
```
# carbon-lookup foo.bar
10.1.1.211:2004:graphite-node-0
10.1.1.209:2004:graphite-node-2
```

good metric:
```
# carbon-lookup local.random.diceroll
10.1.1.210:2004:graphite-node-1
10.1.1.211:2004:graphite-node-0
```

**Comment by piotr1212** [comment]
This is intended. Lookup calculates on which node a metric will be, does not actually check if it is there.
