### ISSUE TITLE
support other consistent hashing algorithms ?

### ISSUE THREAD

**Issue by filippog** [graphite-project/carbonate#43]
hi,
as pointed out in the README ports and "labels" are not taken into consideration when running the consistent hashing algo (as #38 found out too)
I think it'd make sense to support other hashing implementations, e.g. fnv1a would make carbonate compatible with https://github.com/grobian/carbon-c-relay which in turn would allow hashing ip+port, what do you think?

**Comment by jssjr** [comment]
I'd be happy to field a PR to make the hash algorithm pluggable. This isn't something I personally have a use case for, but it does seem really handy.

**Comment by xyntrix** [comment]
This would be super awesome to support fnv1a_ch out of carbon-c-relay.

**Comment by xyntrix** [comment]
I think I can probably git a PR submitted.  If I take this:
- https://github.com/grobian/carbon-c-relay/blob/master/fnv1a.h
and apply something like this
- https://gist.github.com/vaiorabbit/5670985
- https://gist.github.com/Cilyan/9424144
should be able to create a fnv1a compatible hash.

**Comment by deniszh** [comment]
@xyntrix - did you succeed in that PR by any chance? I want to do that same :)
