### ISSUE TITLE
how to speed up carbon-sync ?

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/carbonate#46]
After a crash in one server with 40000 metrics I've recovered by doing a carbon-sync with another server with all replicated metrics.

The recovery process take as long as 10 hours.

After review the logs for each 1000 recovered metrics.

```
    Rsync time: 143.773407936s
    Merge time: 765.371428013s
    Total time: 909.144835949s
```

Merge time seems to take the 85% of the time.
- there is any way to speed up this process?
- Can I specify to sync only from/to , by examaple from="1 day ago"  to decrease the total taken time?

**Comment by jssjr** [comment]
The best way to speed up carbon-sync is to parallelize it. Break your carbon-list results into chunks and pass that to multiple carbon-sync processes. This will allow the merge process to use multiple cores.

I'm not sure how to handle syncing from a specific point in time, but I think that is an interesting idea. Currently, carbon-sync is rsync'ing the source whisper file from the server and running whisper-fill to merge the data into the target whisper file (or just blindly cp'ing the file if the target doesn't exist.) I'd be open to a PR that added the ability to set upper and lower bounds (probably via epoch values) to whisper-fill. If that works well, then we can sort out how to expose this as options to carbon-sync.

**Comment by toni-moreno** [comment]
when done, I would like to test !! 

Thank you very much !!

**Comment by toni-moreno** [comment]
Hi @jssjr . 
Any advance on this issue ? I need to synchronize tons of whisper files and would like to minimize the synchronization time.

Thank you very much.
