### ISSUE TITLE
option to use whisper.LOCK during sync/fill

### ISSUE THREAD

**Issue by filippog** [graphite-project/carbonate#47]
*splitting this issue from #19 since they are really two different things*

carbonate should use whisper.LOCK if it can during sync/fill like carbon does to prevent corrupting whisper files if multiple writers are present (e.g. carbon-cache and carbonate)

**Comment by filippog** [comment]
hi @jssjr ! thoughts/comments on this? I think it'd be great to have at least for safe operation. I think it should be smarter and retry on lock failure or keep a queue of retries, if the file exists chances are we are going to backfill data and thus can wait for e.g. carbon-cache

**Comment by deniszh** [comment]
Implemented in https://github.com/graphite-project/carbonate/pull/71
