### ISSUE TITLE
Intermittent rsync errors

### ISSUE THREAD

**Issue by bwilder** [graphite-project/carbonate#61]
Hi,
I'm getting intermittent rsync errors while running a script based on the 'Rebalance a cluster' example. The errors look like below:

`WARNING:root:Failed to copy /var/lib/graphite/whisper/myprdbox1/disk/disk/mapper/rootvg-rootlv/avail.wsp! [Errno 2] No such file or directory: '/tmp/tmpgzUPfI/myprdbox1/disk/disk/mapper/rootvg-rootlv/avail.wsp'`

Rerunning the script rarely yields the same errors. Sometimes it finishes cleanly, throwing no errors at all.
Googling and troubleshooting have yet to yield any satisfying results. Do you have any insight into what might cause this behavior? Would this kind of thing happen if attempting to rsync a database that's currently being written to?

If there's specific data I can provide to help narrow the scope, let me know.

Thanks!

**Comment by blacked** [comment]
I have same issue while syncing from old stand alone box to new cluster box.

**Comment by dinapappor** [comment]
I am having the exact same issue as @blacked . Were there ever a fix for this?

**Comment by dinapappor** [comment]
Ok, this was due to not having rsync on original box.

**Comment by deniszh** [comment]
Just additional note - if you use locking you may find libflockit useful to make rsync obey to the locks. Check [this blog](https://www.swiftstack.com/blog/2012/08/15/old-school-monkeypatching/), [flockit repo](https://github.com/smerritt/flockit) and corresponding [issue](https://github.com/graphite-project/carbonate/issues/19) on carbonate project.
