### ISSUE TITLE
Carbonate can't find carbon installed in virtualenv (or non virtualenv on Mac OS X)

### ISSUE THREAD

**Issue by scottcunningham** [graphite-project/carbonate#64]
Hey there,

When I install carbonate in a virtualenv on my local laptop (Mac OS X 10.11) or on a Debian 7 server, carbonate fails to find graphite and errors when I try to run any script:

```
$ carbon-hosts
No bueno. Can't import carbon! (No module named carbon)
```

But I can see that carbon is installed:

```
$ pip freeze | grep carbon
carbon==0.9.15
carbonate==0.2.2
```

The same thing happens on both the Mac OS X and Debian 7 machines. But if I exit the virtualenv on the Debian machine, then `apt-get install graphite-carbon` and install carbonate into global site-packages with `pip install carbonate`, it works:

```
root@test-node01:~# pip install carbonate
[...]
root@test-node01:~# carbon-hosts
Cluster 'main' not defined in /opt/graphite/conf/carbonate.conf  # it works!
```

Similarly, if I install carbon into the global site-packages using pip (after `apt-get purge graphite-carbon` to remove the Debian-packaged version) it also works fine on Debian:

```
root@edge-node01:~# pip install carbon
Downloading/unpacking carbon
[...]
Successfully installed carbon
Cleaning up...
root@edge-node01:~# carbon-hosts
Cluster 'main' not defined in /opt/graphite/conf/carbonate.conf
```

BUT not on Mac OS X:

```
% pip install carbon carbonate  
[...]
% carbon-hosts
No bueno. Can't import carbon! (No module named carbon)
```

Cheers,
@scottcunningham

**Comment by scottcunningham** [comment]
Ping pong. Has this project been abandoned?

**Comment by deniszh** [comment]
Nope. Nothing to say about issue though, sorry.

**Comment by deniszh** [comment]
Disregard that, I have a workaround.
1. `pip uninstall carbon`
2. `sudo pip install carbon --install-option="--prefix=/opt/graphite" --install-option="--install-lib=/opt/graphite/lib"`

It works after such hack.

**Comment by jssjr** [comment]
@scottcunningham - Take a look at [`script/bootstrap`](https://github.com/graphite-project/carbonate/blob/6402ee9b382774ee58a19c68a4d5c709676b1f3d/script/bootstrap) to see how I've worked around some of the path expectations in graphite and carbon inside of a virtualenv.

**Comment by scottcunningham** [comment]
Thanks a lot for the help @deniszh @jssjr! It seems to work fine for me now.

Are there any docs explaining the Carbon import weirdness and how it came about? I'd like to better understand why the problem comes up.

**Comment by deniszh** [comment]
I suspect that problem connected with wheel support in new pip versions. But maybe @jssjr knows more...

**Comment by deniszh** [comment]
We need to mention wheel support disable in installation docs

**Comment by scaleoutsean** [comment]
That workaround also works on Ubuntu 18.04.3
