### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by filippog** [graphite-project/carbonate#75]
Hi!
The latest carbonate release is from 2014, are there plans to release the last commits ? I'm particularly interested in `--lock`.

Thanks!

**Comment by deniszh** [comment]
I created release - https://github.com/graphite-project/carbonate/releases/tag/0.2.3
Will try to upload it to pypi soon

**Comment by filippog** [comment]
awesome! thanks @deniszh for the quick action!

**Comment by deniszh** [comment]
Release is live on PyPi - https://pypi.python.org/pypi/carbonate/0.2.3

PS: I'm terribly sorry, @filippog - looks like I made a typo in your Github username in release notes and I just noticed that.
And it's baked and released now. :(

**Comment by filippog** [comment]
@deniszh no worries at all, also you got right the two other entries :) Thanks again, closing
