### ISSUE TITLE
Is carbonate still considered beta quality?

### ISSUE THREAD

**Issue by ferki** [graphite-project/carbonate#79]
While working on packaging carbonate for Gentoo, one of the developers [expressed concerns](https://bugs.gentoo.org/show_bug.cgi?id=618458#c2) about the following remark in [License and Warnings](https://github.com/graphite-project/carbonate#license-and-warnings) section of the README:

> These tools should be considered beta quality right now

So to decide how to move forward with packaging, I'd like to ask if carbonate is still considered as beta quality software?

**Comment by deniszh** [comment]
We released 1.0.0 (together with Graphite), so, I think we can remove beta sentence now.
/cc @jssjr @iksaif @DanCech 
Will do that if no concerns.

**Comment by jssjr** [comment]
> Will do that if no concerns.

👍 Seems like a good idea.

**Comment by deniszh** [comment]
Done!
