### ISSUE TITLE
Carbon-sieve errors out when results from carbon-list are piped to it.

### ISSUE THREAD

**Issue by ra-dft** [graphite-project/carbonate#88]
While trying to measure time to complete a rebalance in preparation of scaling out our cluster using the example provided.  I'm getting an error from carbon-sieve:

> carbon-list -c /opt/graphite/conf/carbonate.conf -C main -d /opt/graphite/whisper/ | carbon-sieve -c /opt/graphite/conf/carbonate.conf -C fnv -n 172.26.2.28 | carbon-sync -s 172.26.2.28

> Traceback (most recent call last):
  File "/usr/local/bin/carbon-sieve", line 10, in <module>
    load_entry_point('carbonate==1.0.2', 'console_scripts', 'carbon-sieve')()
  File "/usr/local/lib/python2.7/dist-packages/carbonate/cli.py", line 119, in carbon_sieve
    cluster = Cluster(config, args.cluster)
  File "/usr/local/lib/python2.7/dist-packages/carbonate/cluster.py", line 36, in __init__
    r.ring = ConsistentHashRing(hash_type=config.hashing_type(cluster))
TypeError: __init__() takes at least 2 arguments (2 given)

>  ~ # pip show carbonate
---
Name: carbonate
Version: 1.0.2
Location: /usr/local/lib/python2.7/dist-packages
Requires: carbon, whisper

If I'm doing something wrong, please let me know.

**Comment by deniszh** [comment]
Try latest master. If it works - let me know, I'll make a release.
