### ISSUE TITLE
preserving timestamps with sync

### ISSUE THREAD

**Issue by bkez322** [graphite-project/carbonate#94]
I want transferred whisper files to preserve the timestamp of the donor. By default, the files on the recipient node have their mtimes updated to the current time. Options that I would I expect to alter this behavior appear to do nothing.

My command looks like this:

`ssh $OTHER_HOST -- 'carbon-list' | carbon-sync -C $CLUSTER "--rsync-options="-c -s $OTHER_HOST`

I have also tried that command with the `-a` and `-t` flags for rsync-options instead of `-c`.

**Comment by deniszh** [comment]
Well, by default `-azpS` should keep mtime, not sure why it's updated by default. Need to investigate.

**Comment by bkez322** [comment]
Might it be a permissions issue with changing the file timestamp? I don't immediately have the ability to test carbonate with different users and permissions at the moment.
