### ISSUE TITLE
Add LICENSE file to pypi package

### ISSUE THREAD

**Issue by dinapappor** [graphite-project/carbonate#96]
Hi! I am building a port for freebsd. The pypi package does not include a LICENSE file to the package. Is it possible to add this to future release of the pypi package?

**Comment by deniszh** [comment]
#97 should fix this. Will merge and release 1.1.3 together with Graphite 1.1.3

**Comment by dinapappor** [comment]
Thanks for adding LICENSE file. How far are you from release? I am wondering if I should wait for release or add the port with the carbon router hash bug fix backported.

**Comment by deniszh** [comment]
Will make release tomorrow or in 2 days.

**Comment by dinapappor** [comment]
I'll close this since the change was merged and release is imminent.
